### ISSUE TITLE
Paid plan needed 

### ISSUE THREAD

**Issue by Joshua-Ronan-Phillips** [Unitie-FAC/Unitie-MVP#134]

**Comment by officialunitie** [comment]
sure, confirm what details you need from us and the pricing please

**Comment by thegsi** [comment]
@officialunitie Please see the price plans on this page:
https://elements.heroku.com/addons/heroku-redis#pricing
We recommend the Premium 0 plan at $15 a month. Please accept our apologies that this has gone up from $7 per month since the project started. The reason we require this plan is due to 'Persistence' . As you can see this is not now guaranteed on the free Hobby plan. Therefore your data may not be secure in the free plan. This has also changed in recent weeks. 
As your credit card details are already in the system, we just need your permission to upgrade.

**Comment by thegsi** [comment]
@officialunitie  Thanks for this. No details required, pricing in $15 per month. I will use the credit card details that have been entered.

**Comment by officialunitie** [comment]
Cool, you can go ahead and set it up then.

Thanks

**Comment by thegsi** [comment]
@officialunitie  This has been done but we will confirm update on Monday.

**Comment by thegsi** [comment]
@officialunitie  Completed please expect a $15 per month charge on the credit card that Tunde provided.
